name: Deploy back
on:
  push:
    branches:
      - main
    paths:
    - 'back-end/**'
jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./CI/prepare-ssh-keys.sh
    - run: ./CI/deploy-back.sh
